import { useEffect, useState } from 'react'
import { assess, cities, verdict, type Check } from './assessment'
export default function App() {
  const [selected, select] = useState(0)
  const [data, setData] = useState<Record<string, Check[]>>({})
  const [loading, setLoading] = useState(true)
  const [revision, refresh] = useState(0)
  const [now, setNow] = useState(Date.now())
  useEffect(() => { let active = true; setLoading(true); setData({}); Promise.all(cities.map(async city => { const checks = await assess(city); if(active) setData(d => ({...d, [city.name]: checks})) })).finally(() => { if(active) setLoading(false) }); return () => { active = false } }, [revision])
  useEffect(() => { const id = setInterval(() => { setNow(Date.now()); refresh(r => r+1) }, 300000); return () => clearInterval(id) }, [])
  const city = cities[selected]; const checks = data[city.name]?.map(c => c.time && now-Date.parse(c.time)>3*3600000 ? {...c, risk:-1, value:'Outdated'} : c) || []
  const result = verdict(checks); const waiting = loading && !checks.length
  return <div className="shell"><aside><a className="brand" href="#"><span className="logo">t</span>threshold<span className="mini"> / outside</span></a><div className="navlabel">WORKSPACE</div><div className="navactive">◉ &nbsp; Conditions overview</div><div className="aside-bottom"><span className="dot"/> Public environmental feeds<p>Automatic checks every 5 minutes</p></div></aside><main>
    <header><div><span className="breadcrumb">Monitor / Overview</span><h1>Is it safe to go outside?</h1><p>Your local conditions, checked together.</p></div><button disabled={loading} onClick={() => refresh(r=>r+1)}>{loading ? 'Checking feeds…' : '↻ Refresh conditions'}</button></header>
    <div className="locationbar"><label>Monitoring location<select value={selected} onChange={e=>select(Number(e.target.value))}>{cities.map((c,i)=><option key={c.name} value={i}>{c.name}, {c.country}</option>)}</select></label><span>{city.lat.toFixed(2)}° N / {Math.abs(city.lon).toFixed(2)}° {city.lon<0?'W':'E'}<br/>Earthquake radius: 100 km</span></div>
    <section className={`verdict ${waiting?'unknown':result.tone}`} aria-live="polite"><div className="status-symbol">{waiting?'…':result.tone==='good'?'✓':result.tone==='unknown'?'?':'!'}</div><div><span className="eyebrow">OUTDOOR CONDITIONS · {city.name.toUpperCase()}</span><h2>{waiting?'Checking your surroundings…':result.title}</h2><p>{waiting?'Requesting air quality, weather, and seismic data.':result.detail}</p></div><span className="verdict-tag">{waiting?'Updating':result.label}</span></section>
    <div className="section-title"><h2>What’s behind the decision</h2><span>Three independent checks</span></div><section className="checks">{['Air quality','Weather','Earthquakes'].map((name,i)=> { const c=checks[i]; return <article key={name}><div className="check-head"><h3>{name}</h3><span className={`badge ${!c||c.risk<0?'unknown':c.risk===2?'bad':c.risk===1?'warn':'good'}`}>{!c?'Loading':c.risk<0?'Unknown':c.risk===2?'High':c.risk===1?'Caution':'Clear'}</span></div><strong className="reading">{c?.value || '—'}</strong><p>{c?.detail || 'Contacting the data provider…'}</p><div className="check-time">{c?.time ? `Data time: ${new Date(c.time).toLocaleString()}` : 'Awaiting valid data'}</div></article>})}</section>
    <section className="comparison"><div className="section-title"><div><h2>Elsewhere right now</h2><p>Compare actual conditions. No city is preset as safe or unsafe.</p></div><span>LIVE API RESULTS</span></div><div className="city-grid">{cities.map((c,i)=>{ const readings=data[c.name]; const v=verdict(readings||[]); return <button key={c.name} className={i===selected?'city selected':'city'} onClick={()=>select(i)}><div><strong>{c.name}</strong><span>{c.country}</span></div><span className={`badge ${v.tone}`}>{readings?v.label:'Checking…'}</span><div className="city-aqi">{readings?.[0].value || '—'} <span>View location →</span></div></button>})}</div></section>
    <details><summary>How the calculation works</summary><p>The highest applicable risk wins. AQI ≤50 is clear; 51–150 prompts caution; above 150 triggers a high-risk result. Weather triggers high risk at feels-like ≥40°C or ≤−15°C, wind ≥60 km/h, or thunderstorm codes. Caution starts at ≥32°C or ≤0°C, wind ≥35 km/h, or precipitation. Nearby M4.5+ earthquakes prompt local-report review, never an automatic instruction to stay inside. These weather and earthquake limits are transparent project rules, not official safety standards.</p><p>Missing, invalid, or more than three-hour-old readings prevent a favorable result. Official emergency warnings, UV, local hazards, and individual health needs are not assessed.</p></details>
    <footer><span>Built by Kyle · Environmental monitoring project</span><span>Sources: <a href="https://open-meteo.com/en/docs/air-quality-api">CAMS / Open-Meteo air quality</a> · <a href="https://open-meteo.com/en/docs">Weather</a> · <a href="https://earthquake.usgs.gov">USGS</a></span></footer>
  </main></div>
}
